---
title: "R Notebook"
output: html_notebook
---

```{r}
library(nycflights13)
library(tidyverse)
library(here)
library(janitor)
library(ggplot2)
library(gridExtra)
```

```{r}
file2022 = here("data_raw", "DL_SelectFields2022.zip")
file2020 = here("data_raw", "DL_SelectFields_2020.zip")
file2018 = here("data_raw", "airline_data_2018.zip")
file2017 = here("data_raw", "DL_SelectFields_2017.zip")
df2022_1 <- read_csv(file2022) %>% clean_names()
df2020_1 <- read_csv(file2020) %>% clean_names()
df2018_1 <- read_csv(file2018) %>% clean_names()
df2017_1 <- read_csv(file2018) %>% clean_names()
```

```{r}
df2017_2 <- df2017_1 %>% filter(dest=="LGA" | origin=="LGA", passengers>0, carrier=="DL") %>% group_by(month)
df2018_2 <- df2018_1 %>% filter(dest=="LGA" | origin=="LGA", passengers>0, carrier=="DL") %>% group_by(month)
df2020_2 <- df2020_1 %>% filter(dest=="LGA" | origin=="LGA", passengers>0, carrier=="DL") %>% group_by(month)
df2022_2 <- df2022_1 %>% filter(dest=="LGA" | origin=="LGA", passengers>0, carrier=="DL") %>% group_by(month)
```

```{r}
plot2017 <- ggplot(df2017_2, aes(month)) + geom_bar(aes(weight=passengers))
plot2018 <- ggplot(df2018_2, aes(month)) + geom_bar(aes(weight=passengers))
plot2020 <- ggplot(df2020_2, aes(month)) + geom_bar(aes(weight=passengers))
plot2022 <- ggplot(df2022_2, aes(month)) + geom_bar(aes(weight=passengers))
```

```{r}
grid.arrange(plot2017, plot2018, plot2020, plot2022, nrow = 2)
```

